/* Generated by Cython 0.29.19 */

#ifndef __PYX_HAVE__mcycle__methods__heat_transfer
#define __PYX_HAVE__mcycle__methods__heat_transfer

#include "Python.h"

#ifndef __PYX_HAVE_API__mcycle__methods__heat_transfer

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C double __pyx_f_6mcycle_7methods_13heat_transfer_htc(double, double, double, int __pyx_skip_dispatch);
__PYX_EXTERN_C double __pyx_f_6mcycle_7methods_13heat_transfer_dpf(double, double, double, double, double, int, int __pyx_skip_dispatch);
__PYX_EXTERN_C double __pyx_f_6mcycle_7methods_13heat_transfer_lmtd(double, double, double, double, unsigned char, int __pyx_skip_dispatch);

#endif /* !__PYX_HAVE_API__mcycle__methods__heat_transfer */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initheat_transfer(void);
#else
PyMODINIT_FUNC PyInit_heat_transfer(void);
#endif

#endif /* !__PYX_HAVE__mcycle__methods__heat_transfer */
