/* Generated by Cython 0.27.3 */

#ifndef __PYX_HAVE__mcycle__bases__component
#define __PYX_HAVE__mcycle__bases__component


#ifndef __PYX_HAVE_API__mcycle__bases__component

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C double runBounds[2];

#endif /* !__PYX_HAVE_API__mcycle__bases__component */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initcomponent(void);
#else
PyMODINIT_FUNC PyInit_component(void);
#endif

#endif /* !__PYX_HAVE__mcycle__bases__component */
