/* Generated by Cython 0.28.6 */

#ifndef __PYX_HAVE__mcycle__utils__conversions
#define __PYX_HAVE__mcycle__utils__conversions


#ifndef __PYX_HAVE_API__mcycle__utils__conversions

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C double m32L(double, int __pyx_skip_dispatch);
__PYX_EXTERN_C double m32galUS(double, int __pyx_skip_dispatch);
__PYX_EXTERN_C double m32galImp(double, int __pyx_skip_dispatch);
__PYX_EXTERN_C double L2m3(double, int __pyx_skip_dispatch);
__PYX_EXTERN_C double L2galUS(double, int __pyx_skip_dispatch);
__PYX_EXTERN_C double L2galImp(double, int __pyx_skip_dispatch);
__PYX_EXTERN_C double galUS2m3(double, int __pyx_skip_dispatch);
__PYX_EXTERN_C double galUS2L(double, int __pyx_skip_dispatch);
__PYX_EXTERN_C double galUS2galImp(double, int __pyx_skip_dispatch);
__PYX_EXTERN_C double galImp2m3(double, int __pyx_skip_dispatch);
__PYX_EXTERN_C double galImp2L(double, int __pyx_skip_dispatch);
__PYX_EXTERN_C double galImp2galUS(double, int __pyx_skip_dispatch);

#endif /* !__PYX_HAVE_API__mcycle__utils__conversions */

/* WARNING: the interface of the module init function changed in CPython 3.5. */
/* It now returns a PyModuleDef instance instead of a PyModule instance. */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initconversions(void);
#else
PyMODINIT_FUNC PyInit_conversions(void);
#endif

#endif /* !__PYX_HAVE__mcycle__utils__conversions */
